### PR TITLE
Agent aggregation source

### PR DESCRIPTION
**Pull request by christian-pinto**
This PR adds support for registering a new aggregation source whenever an event with `MessageId: Manager.1.0.AggregationSourceDiscovered` is received. As of today, aggregation sources are the best candidate for representing a new Fabric agent registering with the OFMF.

This functionality can be tested by sending a POST request to `host:port/EventListener` with the below payload:

```json
{
    "@odata.type": "#Event.v1_7_0.Event",
    "Id": "1",
    "Name": "Manager Created",
    "Context": "",
    "Events": [{
      "EventType": "Other",
      "EventId": "4594",
      "Severity": "Ok",
      "Message": "New Manager Available at FQDN http://foo.bar.org and Port 1234 ",
      "MessageId": "Manager.1.0.AggregationSourceDiscovered",
      "MessageArgs": [ "http://foo.bar.org", "1234" ],
      "OriginOfCondition": {
        "@odata.id": "/redfish/v1/Managers/Manager1"
      }}
    ]
}
```

### CODE REVIEW

**Comment by mgazz** [comment]
Add steps to test the new event.

**Comment by rherrell** [comment]
I submitted the above POST and payload to my local build of this branch and the new AggregationSource object 'Manager1'  was placed in the AggregationService/AggregationSources/Manager1 directory under Resources and I received a SUCCESS response.  However, I think there are two problems with the Manager1 object that got created.

Here is the payload submitted (per above)
{

    "@odata.type": "#Event.v1_7_0.Event",
    "Id": "1",
    "Name": "Manager Created",
    "Context": "",
    "Events": [{
      "EventType": "Other",
      "EventId": "4594",
      "Severity": "Ok",
      "Message": "New Manager Available at FQDN http://foo.bar.org and Port 1234 ",
      "MessageId": "Manager.1.0.AggregationSourceDiscovered",
      "MessageArgs": [ "http://foo.bar.org", "1234" ],
      "OriginOfCondition": {
        "@odata.id": "/redfish/v1/Managers/Manager1"
      }}
    ]
}

Here is the Manager1 object that was POSTed to the Resources/AggregationService/AggregationSources/Manager1 directory of emulator in response:

{
    "@Redfish.Copyright": "Copyright 2Manager114-2Manager121 SNIA. All rights re
served.",
    "@odata.id": "/redfish/v1/AggregationService/AggregationSources/Manager1",
    "@odata.type": "#AggregationSource.v1_2_Manager1.AggregationSource",
    "HostName": "1234",
    "Id": "Manager1",
    "Links": {
        "ConnectionMethod": {},
        "ResourcesAccessed": []
    },
    "Name": "Agent Manager1"
}

Concern 1:  The above Manager1 object was NOT POSTed to where the payload OriginOfCondition property specified.  If the OriginOfCondition URI is supposed to be followed literally, the event handler is not putting the object in the correct space.  I don't know if the event handler is allowed to assume a different path than what it is handed or not.  The example payload is therefore confusing.

Concern 2:  Also note that the Manage1 object lists "HostName":"1234", not ""http://foo.bar.org":"1234" for what I assumed would be the URL of the Agent sending the event.  

Are these real problems or am I miss-interpreting what the input and output are supposed to be?

**Comment by christian-pinto** [comment]
@mgazz I have another PR #20 open for adding unittests. I'd prefer to have that one accepted first and then rebase this PR and add a unittest.

@rherrell Replying to both your concerns:

- Concern 1: The idea  would be that when an agent is discovered via the `AggregationSourceDiscovered` event a new aggregation source is added under `AggregationService/AggregationSources` as this is the place and objects we agreed we would use for representing a fabric/hardware agent. The event however carries the `OriginOfCondition` field that then should be used for querying the new Manager object (which is usually something more i the style of a BMC) on the Agent side by fetching `https://HostName/redfish/v1/Managers/Manager1`. This would then create a copy of the manager where you would expect to see it in the Sunfish main tree under `/redfish/v1/Managers/`.
- Concern 2: that was actually a bug in my code while creating the AggregationSource object. Thanks for pointing it out. I have fixed it and pushed a new commit. You can checkout the updated branch to have a look.

Does the reasoning related to Concern 1 make sense to you?

**Comment by mjaguil** [comment]
Guys

I am tied up working on the Composability Manager design……. I’ll try to take a look, as well, this weekend.  What I would like to do is to put my Composability Manager at Sunfish, and these changes, and see what things look like.  I am finishing up the first iteration of the Use-Case descriptions for the Graph commands and I am working my way up the stack.

Mike

From: Christian Pinto ***@***.***>
Date: Friday, August 11, 2023 at 1:20 AM
To: OFMFWG/OFMF-Reference ***@***.***>
Cc: Aguilar, Michael J. ***@***.***>, Review requested ***@***.***>
Subject: [EXTERNAL] Re: [OFMFWG/OFMF-Reference] Agent aggregation source (PR #19)

@mgazz<https://github.com/mgazz> I have another PR #20<https://github.com/OFMFWG/OFMF-Reference/pull/20> open for adding unittests. I'd prefer to have that one accepted first and then rebase this PR and add a unittest.

@rherrell<https://github.com/rherrell> Replying to both your concerns:

  *   Concern 1: The idea would be that when an agent is discovered via the AggregationSourceDiscovered event a new aggregation source is added under AggregationService/AggregationSources as this is the place and objects we agreed we would use for representing a fabric/hardware agent. The event however carries the OriginOfCondition field that then should be used for querying the new Manager object (which is usually something more i the style of a BMC) on the Agent side by fetching https://HostName/redfish/v1/Managers/Manager1. This would then create a copy of the manager where you would expect to see it in the Sunfish main tree under /redfish/v1/Managers/.
  *   Concern 2: that was actually a bug in my code while creating the AggregationSource object. Thanks for pointing it out. I have fixed it and pushed a new commit. You can checkout the updated branch to have a look.

Does the reasoning related to Concern 1 make sense to you?

**Review by dledford — APPROVED** [review]

**Review by rherrell — APPROVED** [review]
It looks good now.

**Pull request merged**
